version: '3'
services:
  
  mongodb:
    restart: always
    image: mongo
    container_name: mongo_db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=senha123
      - MONGO_INITDB_DATABASE=accounts
    ports: 
      - 27017:27017

product:
    image: ecomm/product
    build: product
    volumes:
      - ./product:/app
    ports:
      - 3000:3000

account:
    image: ecomm/account
    build: account
    volumes:
       - ./account:/app
    ports:
      - 3000:3000

    



 

  