version: '3'
services:

  account:
    image: eccom/account
    build: account
    ports:
      - 3000:3000
      
  account-database:
    image: mongo
    container_name: account-database   
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=senha123 
      - MONGO_INITDB_DATABASE=accounts
    ports:
      - 27017:27017

  product:
    image: eccom/product
    build: product
    ports:
      - 3001:3000


# para baixar imagem :    docker build . -t eccom/product
# para baixar imagem :    docker build . -t eccom/account 


    



 

  